version: '3.8'
services:
  au-exam-finder:
    image: ghcr.io/froemosen/au-exam-finder:latest
    build: .
    container_name: au-exam-finder
    restart: always
    expose:
      - "5002"          # internal port for cloudflared to reach
    environment:
      - FLASK_ENV=production
